Restart enable touchups
badgerloop-software/sc1-driver-io pull request #11
Opened 2022-09-01 17:27 UTC by jrvollmer

Touched up appearance and contents of restart enable popup
Fixed fan speed warnings
Updated speed to float (in all occurrences) to match data format

2022-10-11 02:33 UTC, EUdds requested changes

2022-10-11 02:33 UTC, EUdds commented on DataProcessor/DataGen.cpp
> +float lastSpeed=0;
Lets avoid global variables wherever possible

2022-10-11 02:33 UTC, EUdds commented on DataProcessor/DataGen.cpp
> +            } else if(names[i] == "speed") {
Future ticket - but this if/else tree is getting mighty long, we should look at more efficient ways to do this

2022-10-11 02:33 UTC, EUdds commented on DataProcessor/DataUnpacker.cpp
> +    this->restart_enable = battery_eStop || driver_eStop || external_eStop || imd_status || !door || crash || mcu_check || restart_enable;
This also do be mighty long - possible place for a function

2022-10-11 02:33 UTC, EUdds commented on DataProcessor/DataUnpacker.h
> +    float speed, accelerator, soc, mppt_current_out, pack_voltage, pack_current, pack_temp, motor_temp, driverIO_temp, mainIO_temp, cabin_temp, string1_temp, string2_temp, string3_temp;
```suggestion
    float speed, accelerator;
    float soc;
    float mppt_current_out;
    float pack_voltage, pack_current;
    float pack_temp, motor_temp, driverIO_temp, mainIO_temp, cabin_temp;
    float string1_temp, string2_temp, string3_temp;
```

2022-10-11 02:33 UTC, EUdds commented on DataProcessor/DataUnpacker.h
> +    bool headlights, cruise, left_turn, right_turn, hazards, mainIO_heartbeat, eng_dash_commfail=1;
```suggestion
    bool headlights, cruise, left_turn, right_turn, hazards, mainIO_heartbeat;
    bool eng_dash_commfail=1;
```

2022-10-22 16:40 UTC, jrvollmer commented on DataProcessor/DataGen.cpp
> +            } else if(names[i] == "speed") {
Ticket for improving DataGen has been added to Jira

2022-10-31 16:17 UTC, EUdds requested changes
Almost perfect

2022-10-31 16:17 UTC, EUdds commented on DataProcessor/DataGen.cpp
> +                bool error = (rand()%700+1 >= 2) && !((errStartTime > time(NULL) - 3) && (errPos != std::string::npos));
Let's remove magic numbers or at least make a function to tell me what is going on here

2022-10-31 16:17 UTC, EUdds commented on DataProcessor/DataGen.cpp
> +                bool error = (rand()%700+1 <= 2) || ((errStartTime > time(NULL) - 3) && (errPos != std::string::npos));
here too

2022-10-31 17:18 UTC, EUdds approved these changes

2022-10-31 22:40 UTC, merged